# Generated by Django 4.1 on 2022-09-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameid',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
