# Generated by Django 4.1 on 2022-09-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_game_gameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='background',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
